# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - armada-go-docker-build-gate-ubuntu_focal
        # disable for now until jammy jobs are configured
        #- armada-go-airskiff-deployment-focal

    gate:
      jobs:
        - armada-go-docker-build-gate-ubuntu_focal

    post:
      jobs:
        - armada-go-docker-publish-ubuntu_focal


- nodeset:
    name: armada-go-single-node-focal
    nodes:
      - name: primary
        label: ubuntu-focal

- job:
    name: armada-go-base
    abstract: true
    roles:
      - zuul: openstack/openstack-helm-infra
      - zuul: zuul/zuul-jobs
    required-projects:
      - name: openstack/openstack-helm
      - name: openstack/openstack-helm-infra
      - name: openstack/openstack-helm-plugin
      - name: airship/treasuremap
        override-checkout: v1.9
    irrelevant-files: &irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^deckhand/tests/unit/.*$
    timeout: 10800
    pre-run:
      - tools/gate/playbooks/prepare-hosts.yaml
      - tools/gate/playbooks/mount-volumes.yaml
      - tools/gate/playbooks/deploy-env.yaml
    run:
      - tools/gate/playbooks/airship-run-scripts.yaml
    post-run:
      - tools/gate/playbooks/osh-infra-collect-logs.yaml
    vars:
      extra_volume:
        size: 80G
        type: Linux
        mount_point: /opt/ext_vol
      docker:
        root_path: "/opt/ext_vol/docker"
      containerd:
        root_path: "/opt/ext_vol/containerd"
      kubeadm:
        pod_network_cidr: "10.244.0.0/16"
        service_cidr: "10.96.0.0/16"
      osh_plugin_repo: "{{ zuul.project.src_dir }}/../../openstack/openstack-helm-plugin"
      loopback_setup: true
      loopback_device: /dev/loop100
      loopback_image: "/opt/ext_vol/openstack-helm/ceph-loop.img"
      ceph_osd_data_device: /dev/loop100
      kube_version_repo: "v1.29"
      kube_version: "1.29.5-1.1"
      calico_setup: true
      calico_version: "v3.27.0"
      cilium_setup: false
      cilium_version: "1.15.6"
      helm_version: "v3.6.3"
      yq_version: "v4.6.0"
      crictl_version: "v1.26.1"
      zuul_osh_relative_path: ../../openstack/openstack-helm
      zuul_osh_infra_relative_path: ../../openstack/openstack-helm-infra
      zuul_treasuremap_relative_path: ../../airship/treasuremap
      gate_scripts_relative_path: ../../openstack/openstack-helm-infra
      run_helm_tests: "no"

- job:
    name: armada-go-airskiff-deployment-focal
    nodeset: treasuremap-airskiff-1node-ubuntu_focal
    description: |
      Deploy Memcached using Airskiff and submitted Armada-go changes.
    parent: armada-go-base
    vars:
      site: airskiff
      HELM_ARTIFACT_URL: https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz
      HTK_COMMIT: 05f2f45971abcf483189358d663e2b46c3fc2fe8
      OSH_INFRA_COMMIT: 05f2f45971abcf483189358d663e2b46c3fc2fe8
      OSH_COMMIT: 049e679939fbd3b0c659dd0977911b8dc3b5a015
      CLONE_ARMADA_GO: false
      DISTRO: ubuntu_focal
      DOCKER_REGISTRY: localhost:5000
      MAKE_ARMADA_GO_IMAGES: true
      USE_ARMADA_GO: true
      gate_scripts_relative_path: ../../airship/treasuremap
      gate_scripts:
        - ./tools/deployment/airskiff/developer/000-prepare-k8s.sh
        - ./tools/deployment/airskiff/developer/009-setup-apparmor.sh
        - ./tools/deployment/airskiff/developer/000-clone-dependencies.sh
        - ./tools/deployment/airskiff/developer/020-setup-client.sh
        - ./tools/deployment/airskiff/developer/015-make-all-charts.sh
        - ./tools/deployment/airskiff/developer/017-make-all-images.sh
        - ./tools/deployment/airskiff/developer/025-start-artifactory.sh
        - ./tools/deployment/airskiff/developer/026-reduce-site.sh
        - ./tools/deployment/airskiff/developer/027-enable-armada-operator.sh
        - ./tools/deployment/airskiff/developer/030-armada-bootstrap.sh
        - ./tools/deployment/airskiff/developer/100-deploy-osh.sh
        - ./tools/deployment/airskiff/common/os-env.sh
        - ./tools/gate/wait-for-shipyard.sh
    irrelevant-files: *irrelevant-files

- job:
    name: armada-go-docker-build-gate-ubuntu_focal
    timeout: 3600
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-go-single-node-focal
    vars:
      publish: false
      distro: ubuntu_focal
      tags:
        dynamic:
          patch_set: true


- job:
    name: armada-go-docker-publish-ubuntu_focal
    timeout: 3600
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: armada-go-single-node-focal
    secrets:
      - airship_armada_go_quay_creds
    vars:
      publish: true
      distro: ubuntu_focal
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest


- secret:
    name: airship_armada_go_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - WT0T3twqEWlkYWkvqmuWvvU/cYXMVurCPjELm0ilZqVBBj9traoHaUgURfYiNJSu6+u+X
          vSugo9uaPgCXM5oQbAyWmtwDH+WHVOmdflx+Q2usmaym7JEET+PYh7DEKsrf3/YRtotn3
          3r8hEXFbaq0+k5MJdc+byQ6CX2PS2W4I8TTRbH+jMDEDttEAXNDpG1C63Geol9deo7c2u
          eQXdzTVcyZ+fn0/nb8bMdAjC+KpWCpU6O2/kMYStdDQYr105JYD1e36YVeGheSDAHqHIj
          1LDHqtjGMeiliimizZ08Lero/yjZiUpQCUGVYqyqi9Tpk5OmecJR9ub0W5pTBPmEMkbiN
          R/8owZMczjWdhD7/Vej9rJAu8iHGnRMJoWYCtLD0De0q6OxQEpSWJl6c7aKsmRorAB3Jt
          sM+GuVwEBllaj67l176Ql4T662zIBVaSUckcsVjQef+JMMj6CKgF+U43pylwFUk/ilnP5
          HJfo8AUtW1P5hpU8xLB4mcS1h5K0ynneWIydiB2aUBsQ34e0T/u1OLfKiLdMBaaPS4Olu
          ks16VnS1VDNXlt0hKEylS4IX77oxtXnRnFpV/3Z3ohlrccvT23FiUr2k0maFTsqQYBs2F
          KJxMTtI/x9G4kk7FtZKyg2w6BYhEgOhmajcqksfEGSgytmhugVq6RC22hHROTM=
      password: !encrypted/pkcs1-oaep
        - bNJ9MY8MvMpwIsvGmY9GsZz1b9XCUeOAlpvL/KAXRGT7sBjt15nvobF+Y/RXjGia+kq/C
          Y8Yz8DEwHAZ9EjqsY20uhoIC89ArjziGxq+ZFl89HHvmWkgs+TYuBh9A0MZUiAOJNkJR4
          yQIWPYvfzknutFqZXGzQ2GPGvp+Lk45PZJs4io91+WQX1DT16fdWpB/CtVfZCrFOyLswM
          58f+K56wf+I2tly9KoAp83gYVE+mGwkqqBUdv6jNcnm9/UMxTGFj1zgKNJdF0sSpT1T1I
          DwynMkKDcvJCsUoH0S0EO/JYd2ne5VsKrI5/4EU2gmBrvvQFyCqccjYHc3557TN+bAe0H
          6xtQSZfM31i/IiGBhR1fqQbyAWVmA27i5pmn5TcekI7YpELCeoIRY5M/BQ5slqpTvbp4C
          VEez4iQvXoHepfRtpFN3/zATFolTqhCldJN+bh6wdg3d8lSecsetD6cU3Fm7aHJuLYoSr
          a4xPhx6s7B1J6wq0P14ADGl5/0CmzeZ3uGw94PRGvg8YAWswUV/DXWogbOH/EEStdsOia
          JaXpU/oVkmC5NcIp3A+6F3NCft8gQCTKecoFBt9/7suvjmCIY9y26SBQ0gOHEjbUzfikT
          FuwYIUDaaLDU+Dz+PfdrKSM63O/uBhrDO+yo+ovqu5PPLksBu42sOrZleAbZIA=
